apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fedilpd.fullname" . }}-config
  labels:
    {{- include "fedilpd.labels" . | nindent 4 }}
data:
  env.yaml: {{ .Values.env | toYaml | b64enc }} 
